import React, { useState, useRef } from 'react';
import { UploadCloud, FileText, BrainCircuit, Loader2, Sparkles, AlertCircle } from 'lucide-react';
import { GoogleGenerativeAI } from '@google/generative-ai';

const ReportAnalyzer = () => {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState('');
  const [error, setError] = useState('');
  const fileInputRef = useRef(null);

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      setFile(selectedFile);
      setError('');
      setAnalysis(''); // clear previous
    } else {
      setError('Please upload a valid PDF file.');
      setFile(null);
    }
  };

  const handleDragOver = (e) => {
    e.preventDefault();
  };

  const handleDrop = (e) => {
    e.preventDefault();
    const droppedFile = e.dataTransfer.files[0];
    if (droppedFile && droppedFile.type === 'application/pdf') {
      setFile(droppedFile);
      setError('');
      setAnalysis('');
    } else {
      setError('Please drop a valid PDF file.');
    }
  };

  const analyzeReport = async () => {
    if (!file) return;

    setLoading(true);
    setError('');

    try {
      // 1. Read file as Base64
      const reader = new FileReader();
      reader.readAsDataURL(file);

      reader.onload = async () => {
        try {
          const base64String = reader.result.split(',')[1];

          // 2. Initialize Gemini AI
          const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
          if (!apiKey) {
            throw new Error("Gemini API key is missing. Please check your .env file.");
          }

          const genAI = new GoogleGenerativeAI(apiKey);
          const model = genAI.getGenerativeModel({ model: "gemini-flash-latest" });

          // 3. Prepare Prompt and Data
          const prompt = `
            You are an expert cognitive analyst and psychologist.
            Please read the attached cognitive test report generated by our platform.
            Analyze the user's performance and provide a comprehensive report formatted in clean Markdown.
            Include:
            1. **Overall Summary:** A brief summary of their cognitive profile.
            2. **Key Strengths:** What domains (e.g., Memory, Attention) are they excelling in?
            3. **Areas for Improvement:** Where did they score lower and what does that mean?
            4. **Actionable Recommendations:** Provide 2-3 practical, encouraging tips to help them improve.
            Keep the tone professional, encouraging, and easy to understand.
          `;

          const pdfPart = {
            inlineData: {
              data: base64String,
              mimeType: "application/pdf"
            }
          };

          // 4. Generate Content
          const result = await model.generateContent([prompt, pdfPart]);
          const responseText = result.response.text();

          setAnalysis(responseText);
        } catch (err) {
          console.error("Gemini Analysis Error:", err);
          setError(err.message || "Failed to analyze the report. Please try again.");
        } finally {
          setLoading(false);
        }
      };

      reader.onerror = () => {
        setError("Failed to read the file.");
        setLoading(false);
      };

    } catch (err) {
      console.error(err);
      setError("An unexpected error occurred.");
      setLoading(false);
    }
  };

  // Helper to safely render very basic markdown structure
  const renderMarkdown = (text) => {
    if (!text) return null;

    const lines = text.split('\n');
    return lines.map((line, index) => {
      if (line.startsWith('### ')) {
        return <h4 key={index} className="text-lg font-bold text-white mt-4 mb-2">{line.replace('### ', '')}</h4>;
      }
      if (line.startsWith('## ')) {
        return <h3 key={index} className="text-xl font-bold text-jb-accent mt-6 mb-3">{line.replace('## ', '')}</h3>;
      }
      if (line.startsWith('# ')) {
        return <h2 key={index} className="text-2xl font-black text-white mt-6 mb-4">{line.replace('# ', '')}</h2>;
      }
      if (line.startsWith('**') && line.endsWith('**')) {
        return <p key={index} className="font-bold text-slate-200 mt-2 mb-1">{line.replace(/\*\*/g, '')}</p>;
      }
      if (line.startsWith('- ') || line.startsWith('* ')) {
        // Format bold text within list items
        let content = line.substring(2);
        const parts = content.split(/(\*\*.*?\*\*)/g);

        return (
          <li key={index} className="ml-4 text-slate-300 mb-1 list-disc">
            {parts.map((part, i) => {
              if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={i} className="text-slate-100">{part.slice(2, -2)}</strong>;
              }
              return part;
            })}
          </li>
        );
      }
      if (line.trim() === '') {
        return <br key={index} />;
      }

      // Handle bold text inline
      if (line.includes('**')) {
        const parts = line.split(/(\*\*.*?\*\*)/g);
        return (
          <p key={index} className="text-slate-300 mb-2 leading-relaxed">
            {parts.map((part, i) => {
              if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={i} className="text-slate-100">{part.slice(2, -2)}</strong>;
              }
              return part;
            })}
          </p>
        );
      }

      return <p key={index} className="text-slate-300 mb-2 leading-relaxed">{line}</p>;
    });
  };

  return (
    <div className="w-full max-w-4xl mx-auto my-16 p-6 md:p-8 bg-jb-card/80 backdrop-blur-xl border border-jb-border rounded-3xl shadow-[0_8px_30px_rgba(13,148,136,0.15)] relative overflow-hidden group">
      {/* Glow Line */}
      <div className="absolute top-0 left-0 w-full h-[3px] bg-gradient-to-r from-transparent via-purple-500 to-transparent"></div>

      <div className="text-center mb-8">
        <div className="inline-flex items-center justify-center p-3 bg-purple-500/10 rounded-full mb-4 ring-1 ring-purple-500/30">
          <BrainCircuit className="h-8 w-8 text-purple-400" />
        </div>
        <h2 className="text-3xl md:text-4xl font-black text-white tracking-tight">AI Report Analyzer</h2>
        <p className="text-slate-400 mt-3 text-lg max-w-2xl mx-auto">
          Upload your downloaded cognitive report to receive a personalized, deep-dive analysis powered by Gemini 1.5 AI.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-5 gap-8">

        {/* Upload Section */}
        <div className="md:col-span-2 flex flex-col gap-4">
          <div
            className={`border-2 border-dashed rounded-2xl p-8 flex flex-col items-center justify-center text-center transition-all cursor-pointer h-full min-h-[250px]
              ${file ? 'border-emerald-500/50 bg-emerald-500/5' : 'border-jb-border hover:border-jb-accent/50 bg-black/20 hover:bg-black/40'}`}
            onDragOver={handleDragOver}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
          >
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileChange}
              accept=".pdf,application/pdf"
              className="hidden"
            />

            {file ? (
              <>
                <FileText className="h-12 w-12 text-emerald-400 mb-3" />
                <p className="text-white font-medium mb-1 truncate w-full px-4">{file.name}</p>
                <p className="text-emerald-400/80 text-xs tracking-wide uppercase">Ready for analysis</p>
                <p className="text-slate-500 text-xs mt-4">Click to change file</p>
              </>
            ) : (
              <>
                <UploadCloud className="h-12 w-12 text-slate-400 mb-3 group-hover:text-jb-accent transition-colors" />
                <p className="text-white font-medium mb-1">Upload your PDF Report</p>
                <p className="text-slate-400 text-sm mb-4">Drag and drop or click to browse</p>
                <span className="px-3 py-1 bg-black/50 border border-slate-700 rounded text-xs text-slate-300">.PDF only</span>
              </>
            )}
          </div>

          {error && (
            <div className="flex items-center gap-2 p-3 bg-red-900/20 border border-red-500/30 rounded-xl text-red-400 text-sm">
              <AlertCircle size={16} /> {error}
            </div>
          )}

          <button
            onClick={analyzeReport}
            disabled={!file || loading}
            className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-purple-600 to-jb-accent hover:from-purple-500 hover:to-jb-accent-hover text-white py-4 rounded-xl font-bold transition-all disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-[0_0_20px_rgba(168,85,247,0.4)]"
          >
            {loading ? (
              <>
                <Loader2 size={20} className="animate-spin" /> Analyzing Report...
              </>
            ) : (
              <>
                <Sparkles size={20} /> Generate AI Insights
              </>
            )}
          </button>
        </div>

        {/* Results Section */}
        <div className="md:col-span-3">
          <div className="bg-black/30 border border-jb-border rounded-2xl p-6 h-full min-h-[300px] max-h-[600px] overflow-y-auto custom-scrollbar">
            {analysis ? (
              <div className="animate-fade-in pr-2">
                {renderMarkdown(analysis)}
              </div>
            ) : loading ? (
              <div className="h-full flex flex-col items-center justify-center text-slate-400 gap-4 animate-pulse">
                <BrainCircuit className="h-12 w-12 text-purple-400/50" />
                <p>Gemini is reviewing your test history...</p>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-slate-500 gap-3">
                <Sparkles className="h-10 w-10 opacity-30" />
                <p className="text-sm">Your AI-generated insights will appear here.</p>
              </div>
            )}
          </div>
        </div>

      </div>
    </div>
  );
};

export default ReportAnalyzer;
